import { useState } from 'react'
import type { ConnectionState, ErrorEvent, SessionSnapshot } from '../shared/types.js'
import { categoryText, eventSummary, labels, type UiLanguage } from './i18n.js'

export const ui: Record<string, import('react').CSSProperties> = {
  panel: { position: 'absolute', top: 42, width: 390, height: 620, minWidth: 320, minHeight: 360, maxWidth: 'calc(100vw - 16px)', maxHeight: 'calc(100vh - 58px)', resize: 'both', overflow: 'auto', border: '1px solid var(--dsw-alias-border-l2, #737373)', borderRadius: 12, background: 'var(--dsw-alias-bg-layer-2, Canvas)', color: 'var(--dsw-alias-label-primary, CanvasText)', boxShadow: '0 18px 60px var(--dsw-alias-bg-mask-3, #0008)' },
  header: { display: 'flex', justifyContent: 'space-between', padding: 14, borderBottom: '1px solid var(--dsw-alias-border-l2, #737373)', touchAction: 'none' },
  section: { padding: '4px 12px 8px' }, h2: { fontSize: 12, textTransform: 'uppercase', letterSpacing: '.05em', color: 'var(--dsw-alias-label-secondary, GrayText)' },
  card: { display: 'flex', width: '100%', flexDirection: 'column', gap: 4, textAlign: 'left', padding: 10, marginBottom: 7, border: '1px solid var(--dsw-alias-border-l2, #737373)', borderRadius: 8, background: 'var(--dsw-alias-bg-layer-3, Canvas)', color: 'inherit', cursor: 'pointer' },
  details: { margin: 12, padding: 10, border: '1px solid var(--dsw-alias-border-l2, #737373)', borderRadius: 8 }, button: { border: '1px solid var(--dsw-alias-border-l2, #737373)', borderRadius: 7, padding: '6px 9px', background: 'transparent', color: 'inherit', cursor: 'pointer' }, primary: { border: 0, borderRadius: 7, padding: '7px 10px', background: 'var(--dsw-alias-button-info-fill, #2563eb)', color: 'var(--dsw-static-neutral-00, white)', cursor: 'pointer' },
  pre: { maxHeight: 220, overflow: 'auto', whiteSpace: 'pre-wrap', padding: 8, borderRadius: 6, background: 'var(--dsw-alias-markdown-code-block, var(--dsw-alias-bg-module-platform, Canvas))', fontSize: 11 },
}

export function ConnectionBadge({ state, language }: { state: ConnectionState; language: UiLanguage }) { const t = labels[language]; return <span role="status" aria-label={`${t.connection}: ${t[state]}`} style={{ color: state === 'connected' ? 'var(--dsw-alias-state-success-primary, #22c55e)' : state === 'offline' ? 'var(--dsw-alias-state-error-primary, #ef4444)' : 'var(--dsw-alias-state-warn-primary, #f59e0b)' }}>{t[state]}</span> }

export function ErrorList({ title, events, selected, language, onSelect }: { title: string; events: ErrorEvent[]; selected: string | undefined; language: UiLanguage; onSelect(value: string): void }) {
  return <section style={ui.section}><h2 style={ui.h2}>{title} ({events.length})</h2>{events.length ? events.map((event) => <button type="button" key={event.fingerprint} aria-pressed={selected === event.fingerprint} onClick={() => onSelect(event.fingerprint)} style={{ ...ui.card, ...(selected === event.fingerprint ? { borderColor: 'var(--dsw-alias-state-business-primary, #3b82f6)' } : {}) }}><strong>{event.exceptionType}</strong><span>{eventSummary(event, language)}</span><small>{event.language ?? 'unknown'} · {event.file ? `${event.file}${event.line ? `:${event.line}${event.column ? `:${event.column}` : ''}` : ''}` : categoryText(event.category, language)} · ×{event.occurrences}</small></button>) : <p>{labels[language].empty}</p>}</section>
}

export function ErrorDetails({ event, language, busy, onDiagnose, onResolve, onIgnore, onUnignore }: { event: ErrorEvent; language: UiLanguage; busy: boolean; onDiagnose(): void; onResolve(): void; onIgnore(): void; onUnignore(): void }) {
  const t = labels[language]; const [copied, setCopied] = useState(false)
  const copy = async () => { await navigator.clipboard?.writeText(event.rawContext.join('\n')); setCopied(true); setTimeout(() => setCopied(false), 1200) }
  return <section style={ui.details}><h2 style={ui.h2}>{t.details}</h2><dl><dt>{t.category}</dt><dd>{categoryText(event.category, language)}</dd><dt>{t.language}</dt><dd>{event.language ?? 'unknown'}{event.toolchain ? ` / ${event.toolchain}` : ''}</dd><dt>{t.capture}</dt><dd>{event.captureMode}</dd><dt>{t.firstSeen}</dt><dd>{new Date(event.firstSeenAt).toLocaleString(language === 'zh' ? 'zh-CN' : undefined)}</dd></dl>{event.command && <code>{event.command}</code>}<details><summary>{t.context} ({event.rawContext.length})</summary><pre style={ui.pre}>{event.rawContext.join('\n')}</pre><button type="button" onClick={() => void copy()} style={ui.button}>{copied ? t.copied : t.copy}</button></details>{event.diagnosis && <div><strong>{event.diagnosis.simpleExplanation}</strong><h3>{t.likelyCauses}</h3><ul>{event.diagnosis.likelyCauses.map((x) => <li key={x}>{x}</li>)}</ul><h3>{t.suggestedChecks}</h3><ol>{event.diagnosis.suggestedChecks.map((x) => <li key={x}>{x}</li>)}</ol></div>}{event.diagnosisError && <div role="alert">{event.diagnosisError}</div>}<div style={{ display: 'flex', flexWrap: 'wrap', gap: 7, marginTop: 10 }}><button type="button" disabled={busy} onClick={onDiagnose} style={ui.primary}>{busy ? '...' : t.ai}</button>{event.status === 'active' && <><button type="button" onClick={onResolve} style={ui.button}>{t.resolve}</button><button type="button" onClick={onIgnore} style={ui.button}>{t.ignore}</button></>}{event.status === 'ignored' && <button type="button" onClick={onUnignore} style={ui.button}>{t.unignore}</button>}</div></section>
}

export function Settings({ snapshot, language, onReset }: { snapshot: SessionSnapshot; language: UiLanguage; onReset(): void }) { const t = labels[language]; return <details style={ui.details}><summary>{t.settings}</summary><dl><dt>{t.manualAi}</dt><dd>{snapshot.settings?.enableAiAnalysis ? t.on : t.off}</dd><dt>{t.redaction}</dt><dd>{snapshot.settings?.secretRedaction ? t.on : t.off}</dd><dt>{t.contextLimit}</dt><dd>{snapshot.settings?.maxErrorContextLines} {t.lines}</dd><dt>{t.historyLimit}</dt><dd>{snapshot.settings?.maxResolvedHistory} {t.cards}</dd><dt>{t.ignoredLimit}</dt><dd>{snapshot.settings?.maxIgnoredHistory} {t.cards}</dd></dl><button type="button" onClick={onReset} style={ui.button}>{t.resetLayout}</button></details> }
